/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DatosVariables;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ariel
 */
public class VentanaAjustes extends javax.swing.JFrame {

    /**
     * Creates new form CantEmpleadosHora
     */
    private DefaultTableModel modelo; 
    private DatosVariables datos;
    public VentanaAjustes(DatosVariables datos) {
        this.datos=datos;
        initComponents();
        String cabecera[]={"Tipo de cliente", "Probabilidad", "Demora en seg.", "+/- Tringular"};
        String datosTabla[][]={};
        modelo = new DefaultTableModel(datosTabla, cabecera);
        table.setModel(modelo);
        table.getTableHeader().setFont(new java.awt.Font("Tahoma", 1, 11));
        /*int anchos [] = {160,100,100,100};
        for(int i=0; i<6; i++){
        	table.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }*/
        for(int i=0;i<4;i++){
            double prob=datos.getProbById(i);
            Object[] dt=new Object[]{datos.getDatoTriangular(i).getNombre(), prob,
                datos.getDatoTriangular(i).getValor(), datos.getDatoTriangular(i).getMaxMin()};
            modelo.addRow(dt);
        }
        //System.out.print(Double.parseDouble(modelo.getValueAt(1, 1).toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.88F);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Probabilidad de tipos de cliente y demora en hacer contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo de cliente", "Probabilidad", "Demora en seg.", "+/- Tringular"
            }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setHeaderValue("Tipo de cliente");
            table.getColumnModel().getColumn(1).setHeaderValue("Probabilidad");
            table.getColumnModel().getColumn(2).setHeaderValue("Demora en seg.");
            table.getColumnModel().getColumn(3).setHeaderValue("+/- Tringular");
        }

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Guardar todos los cambios");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setText("Cerrar y restablecer cambios");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnSave))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        actualizarDatosTiposClientes();
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed
    private void actualizarDatosTiposClientes(){
        try {
            for (int i = 0; i < 4; i++) {
                datos.getProbTipoClientes()[i]= Double.parseDouble(modelo.getValueAt(i, 1).toString());
                //
                datos.setDatoTriangular(i, Integer.parseInt(modelo.getValueAt(i, 2).toString()),
                        Integer.parseInt(modelo.getValueAt(i, 3).toString()));
                //System.out.println(datos.getDatoTriangular(i).getNombre()+" : "+datos.getDatoTriangular(i).getValor()+" +/- "+datos.getDatoTriangular(i).getMaxMin());
            }
        } catch (Exception e) {
        }
    }
    
    /*public static void main(String args[]) {
        try {//RavenGraphiteGlassSkin este es negro
            org.jvnet.substance.SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin");//MistAquaSkin GreenMagicSkin NebulaSkin
            DatosVariables dv=new DatosVariables();
            VentanaAjustes m=new VentanaAjustes(dv);m.setLocationRelativeTo(null);m.setVisible(true);
        }catch (Exception e) {}
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
